nelmio_api_doc:
  documentation:
    schemes: [ http ]
    info:
      title: SymApi api
      description: SymApi systems api.
      version: 0.0.1
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'Authorization: Bearer {jwt}'
        name: Authorization
        in: header
    security:
      - Bearer: [ ]
  areas:
    path_patterns: # an array of regexps
      - ^/api(?!/doc$)