version: '3.7'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

services:
  ####################################################
  # app
  ####################################################
  app:
    restart: always
    build:
      context: ./app
      args:
        TZ: ${TZ}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        APP_ENV: ${APP_ENV}
    environment:
      NGINX_HOST: ${HOST_NAME}
      VIRTUAL_HOST: ${HOST_NAME}
    volumes:
      - ./../:/app
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - default

  #####################################################
  # MySQL
  #####################################################
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - './data/mysql:/var/lib/mysql:rw'
    networks:
      - default

volumes:
  mysql:
    driver: local
  app:
    driver: local

