#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login

api:
  prefix: /api/v1
  resource: ../src/Api/
  type: annotation

app.swagger:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }